name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p ~/expense-tracker-backend
            cd ~/expense-tracker-backend

            # Install and configure NVM properly in a single command
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] || (curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash)
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install Node.js and global tools in a single operation
            nvm install --lts

            # Install global tools with Node.js available
            npm install -g npm@latest pnpm @nestjs/cli pm2

            # Install dependencies and build the application
            pnpm install
            pnpm build
            pnpm prisma migrate deploy

            # First check if the process exists and handle it appropriately
            if pm2 list | grep -q "expense-tracker-api"; then
              echo "Stopping existing application..."
              pm2 delete "expense-tracker-api"
            fi

            # Start the application with the new code
            echo "Starting application with updated code..."
            pm2 start dist/src/main.js --name "expense-tracker-api"
            pm2 save

            echo "Deployment completed successfully!"
